version: '3'
networks:
  curso_nest_js_network:

services:
   dev:
        container_name: curso_nest_js_api_dev
        image: nestjs-api-dev:1.0.0
        build:
            context: ./.docker/app
            target: development
            dockerfile: ./Dockerfile
        command: npm run start:dev
        ports:
            - 3008:3000
        networks:
            - curso_nest_js_network
        volumes:
            - .:/home/node/app/
        restart: unless-stopped
   prod:
        container_name: curso_nest_js_api_prod
        image: nestjs-api-prod:1.0.0
        build:
            context: ./.docker/app
            target: production
            dockerfile: ./Dockerfile
        command: npm run start:prod
        ports:
            - 3000:3000
            - 9229:9229
        networks:
            - curso_nest_js_network
        volumes:
            - .:/home/node/app/
        restart: unless-stopped